name: Build APK com Buildozer

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Instalar dependências
        run: |
          sudo apt update
          sudo apt install -y python3-pip zip unzip openjdk-17-jdk wget
          python3 -m pip install --upgrade pip
          pip install buildozer cython virtualenv
          wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O cmdline-tools.zip
          unzip -q cmdline-tools.zip -d $HOME/.android/cmdline-tools
          mv $HOME/.android/cmdline-tools/cmdline-tools $HOME/.android/cmdline-tools/latest
          yes | $HOME/.android/cmdline-tools/latest/bin/sdkmanager --sdk_root=$HOME/.android \
            "platform-tools" \
            "platforms;android-33" \
            "build-tools;33.0.2" \
            "cmdline-tools;latest" \
            "ndk;25.1.8937393"

      - name: Configurar variáveis de ambiente Android
        run: |
          echo "ANDROID_HOME=$HOME/.android" >> $GITHUB_ENV
          echo "ANDROID_SDK_ROOT=$HOME/.android" >> $GITHUB_ENV
          echo "$HOME/.android/platform-tools" >> $GITHUB_PATH
          echo "$HOME/.android/cmdline-tools/latest/bin" >> $GITHUB_PATH
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Construir APK com Buildozer
        run: |
          buildozer android debug

      - name: Fazer upload do APK
        uses: actions/upload-artifact@v3@8e4f47c65e03c556fbf1b97b777c6c62497379c1
        with:
          name: app-debug.apk
          path: bin/*.apk
          
