name: Build VS Creator APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar dependências do sistema e Buildozer
        run: |
          sudo apt update
          sudo apt install -y \
            build-essential \
            ccache \
            git \
            zip \
            unzip \
            openjdk-11-jdk \
            python3-pip \
            python3-dev \
            libffi-dev \
            libssl-dev \
            libnss3
          pip install --upgrade pip
          pip install cython
          pip install buildozer

      - name: Build APK
        run: |
          buildozer android debug

      - name: Fazer upload do APK
        uses: actions/upload-artifact@v4
        with:
          name: vscreator-apk
          path: bin/*.apk
          
