name: Build APK with Buildozer

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Instalar dependências
        run: |
          sudo apt update
          sudo apt install -y \
            python3-pip \
            zip \
            openjdk-11-jdk \
            git \
            build-essential \
            libncurses5 \
            libstdc++6 \
            libffi-dev \
            libssl-dev \
            libsqlite3-dev \
            zlib1g-dev \
            libjpeg-dev \
            libfreetype6-dev \
            libpng-dev \
            pkg-config \
            unzip \
            curl \
            liblzma-dev
          pip install --upgrade pip setuptools
          pip install buildozer cython virtualenv

      - name: Criar ambiente virtual
        run: |
          python3 -m venv venv
          source venv/bin/activate
          pip install --upgrade pip

      - name: Compilar APK com Buildozer
        run: |
          source venv/bin/activate
          buildozer android debug

      - name: Upload do APK
        uses: actions/upload-artifact@v3
        with:
          name: vscreator-apk
          path: bin/*.apk
          
