name: Build APK com Buildozer

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Instalar dependências
        run: |
          sudo apt update
          sudo apt install -y python3-pip zip unzip openjdk-17-jdk
          pip3 install --upgrade pip
          pip3 install buildozer cython

      - name: Compilar APK com Buildozer
        run: |
          buildozer android debug

      - name: Fazer upload do APK
        uses: actions/upload-artifact@v4
        with:
          name: vs-creator-apk
          path: bin/*.apk
