name: Build APK com Buildozer

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 45  # Aumentado para builds mais complexos

    steps:
    - uses: actions/checkout@v4

    - name: Instalar dependências
      run: |
        sudo apt-get update -qq
        sudo apt-get install -y --no-install-recommends \
          python3-pip \
          openjdk-17-jdk \
          libffi-dev \
          zlib1g-dev \
          unzip
        python3 -m pip install --quiet --upgrade pip setuptools wheel
        python3 -m pip install --quiet buildozer cython==0.29.36 kivy==2.3.0

    - name: Configurar ambiente Android
      run: |
        mkdir -p ~/.android
        touch ~/.android/repositories.cfg
        echo "sdk.dir=/usr/local/lib/android/sdk" > local.properties

    - name: Limpar espaço
      run: |
        sudo apt-get clean
        sudo rm -rf /var/lib/apt/lists/*
        df -h

    - name: Compilar APK
      id: build
      run: |
        buildozer -v android debug 2>&1 | tee build.log
        
        # Verifica se o APK foi gerado
        APK_PATH=$(find . -name "*.apk" -type f | head -n1)
        if [ -z "$APK_PATH" ]; then
          echo "::error::Nenhum APK encontrado!"
          cat build.log
          exit 1
        fi
        
        echo "APK gerado em: ${APK_PATH}"
        echo "apk_path=${APK_PATH}" >> $GITHUB_OUTPUT

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: vscreator-app
        path: ${{ steps.build.outputs.apk_path }}
        if-no-files-found: error
