name: Build VS Creator APK

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Instalar dependências do sistema
        run: |
          sudo apt update
          sudo apt install -y build-essential git zip unzip \
            openjdk-17-jdk python3 python3-pip \
            libstdc++6 libgtk-3-dev libffi-dev \
            libssl-dev libsqlite3-dev zlib1g-dev \
            libjpeg-dev libfreetype6-dev libncurses5-dev

      - name: Instalar Cython e Buildozer
        run: |
          pip3 install --upgrade pip
          pip3 install cython
          pip3 install buildozer

      - name: Compilar APK com Buildozer (primeira tentativa)
        run: |
          buildozer android debug || true  # ignora erro temporário para instalar aidl

      - name: Corrigir erro do AIDL
        run: |
          echo "Copiando aidl para o local esperado..."
          AIDL_ORIG="$HOME/.buildozer/android/platform/build-tools/33.0.2/aidl"
          AIDL_DEST="$HOME/.buildozer/android/platform/android-sdk/build-tools/33.0.2/"
          mkdir -p "$AIDL_DEST"
          cp "$AIDL_ORIG" "$AIDL_DEST"

      - name: Configurar variáveis de ambiente Android
        run: |
          echo "ANDROID_HOME=$HOME/.buildozer/android/platform/android-sdk" >> $GITHUB_ENV
          echo "ANDROID_SDK_ROOT=$HOME/.buildozer/android/platform/android-sdk" >> $GITHUB_ENV
          echo "$HOME/.buildozer/android/platform/android-sdk/platform-tools" >> $GITHUB_PATH
          echo "$HOME/.buildozer/android/platform/android-sdk/build-tools/33.0.2" >> $GITHUB_PATH

      - name: Compilar APK com Buildozer (final)
        run: |
          buildozer android debug

      - name: Fazer upload do APK
        uses: actions/upload-artifact@v4
        with:
          name: vs-creator-apk
          path: bin/*.apk
          
