name: Build APK

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
    - uses: actions/checkout@v4

    - name: Setup environment
      run: |
        sudo apt-get update -qq
        sudo apt-get install -y --no-install-recommends \
          openjdk-17-jdk \
          libffi-dev \
          zlib1g-dev \
          unzip \
          git

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install buildozer cython==0.29.36

    - name: Accept Android licenses
      run: |
        mkdir -p ~/.android
        touch ~/.android/repositories.cfg
        yes | ~/.buildozer/android/platform/android-sdk/cmdline-tools/latest/bin/sdkmanager --licenses

    - name: Build APK
      run: |
        buildozer -v android debug 2>&1 | tee build.log
        find . -name "*.apk" -type f

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: vscreator-app
        path: bin/*.apk
