name: Build and Upload APK

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
    - uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install system dependencies
      run: |
        sudo apt-get update -qq
        sudo apt-get install -y --no-install-recommends \
          openjdk-17-jdk \
          libffi-dev \
          zlib1g-dev \
          unzip \
          ffmpeg \
          git

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install buildozer cython==0.29.36

    - name: Setup python-for-android
      run: |
        mkdir -p ~/.buildozer/android/platform
        git clone -b develop --depth 1 https://github.com/kivy/python-for-android.git ~/.buildozer/android/platform/python-for-android

    - name: Build APK
      id: build-apk
      run: |
        buildozer -v android debug 2>&1 | tee build.log
        
        APK_PATH=$(find . -name "*.apk" -type f | head -n1)
        if [ -z "$APK_PATH" ]; then
          echo "::error::APK not found!"
          cat build.log
          exit 1
        fi
        
        echo "APK found at: ${APK_PATH}"
        echo "apk_path=${APK_PATH}" >> $GITHUB_OUTPUT

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: vscreator-app
        path: ${{ steps.build-apk.outputs.apk_path }}
