name: Build APK

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar dependências do sistema
        run: |
          sudo apt update
          sudo apt install -y zip unzip openjdk-17-jdk

      - name: Instalar Buildozer
        run: |
          python -m pip install --upgrade pip
          pip install buildozer

      - name: Instalar Android SDK e build-tools 30.0.3 (com aidl)
        run: |
          mkdir -p "$HOME/.android"
          touch "$HOME/.android/repositories.cfg"
          yes | sdkmanager --licenses
          sdkmanager "platform-tools" "platforms;android-30" "build-tools;30.0.3"
          echo "Verificando AIDL:"
          ls $ANDROID_HOME/build-tools/30.0.3/aidl

      - name: Compilar APK com Buildozer
        run: |
          buildozer android debug

      - name: Fazer upload do APK
        uses: actions/upload-artifact@v3
        with:
          name: vs-creator-apk
          path: bin/*.apk
          
