name: Build APK com Buildozer

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar repositório
      uses: actions/checkout@v4  # Atualizado para v4

    - name: Instalar dependências
      run: |
        sudo apt update
        sudo apt install -y python3-pip git zip unzip openjdk-17-jdk libffi-dev
        pip install --upgrade pip setuptools
        pip install buildozer cython==0.29.36

    - name: Configurar Buildozer
      run: |
        buildozer init
        # Adicione aqui qualquer comando de configuração adicional se necessário
        # Exemplo: sed -i 's/#android.accept_sdk_license = False/android.accept_sdk_license = True/' buildozer.spec

    - name: Compilar APK com Buildozer
      run: |
        buildozer -v android debug
        ls -la bin/

    - name: Upload APK gerado
      uses: actions/upload-artifact@v4  # Atualizado para v4
      with:
        name: vscreator-apk
        path: bin/*.apk
