name: Build APK com Buildozer

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar repositório
      uses: actions/checkout@v4

    - name: Instalar dependências
      run: |
        sudo apt update
        sudo apt install -y python3-pip git zip unzip openjdk-17-jdk libffi-dev
        pip install --upgrade pip setuptools
        pip install buildozer cython==0.29.36

    - name: Limpar espaço em disco
      run: |
        sudo apt clean
        sudo rm -rf /usr/local/lib/android/sdk/emulator/
        df -h

    - name: Compilar APK com Buildozer
      run: |
        buildozer -v android debug
        ls -la bin/

    - name: Upload APK gerado
      uses: actions/upload-artifact@v4
      with:
        name: vscreator-apk
        path: bin/*.apk
