name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Instalar dependências
        run: |
          sudo apt update
          sudo apt install -y python3-pip zip unzip openjdk-17-jdk wget
          python3 -m pip install --upgrade pip
          pip install buildozer cython virtualenv
          wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O cmdline-tools.zip
          unzip -q cmdline-tools.zip
          mkdir -p $HOME/.android/cmdline-tools/latest
          mv cmdline-tools/* $HOME/.android/cmdline-tools/latest/
          yes | $HOME/.android/cmdline-tools/latest/bin/sdkmanager --sdk_root=$HOME/.android "platform-tools" "platforms;android-33" "build-tools;33.0.2"

      - name: Configurar variáveis de ambiente Android
        run: |
          echo "ANDROID_HOME=$HOME/.android" >> $GITHUB_ENV
          echo "$HOME/.android/platform-tools:$HOME/.android/cmdline-tools/latest/bin" >> $GITHUB_PATH

      - name: Construir APK com Buildozer
        run: |
          buildozer android debug

      - name: Fazer upload do APK
        uses: actions/upload-artifact@v4
        with:
          name: vscreator-apk
          path: bin/*.apk
          
