name: Build VS Creator APK

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Instalar dependências do sistema
        run: |
          sudo apt update
          sudo apt install -y build-essential git zip unzip \
            openjdk-17-jdk python3 python3-pip \
            libstdc++6 libgtk-3-dev libffi-dev \
            libssl-dev libsqlite3-dev zlib1g-dev \
            libjpeg-dev libfreetype6-dev libncurses5-dev \
            libbz2-dev liblzma-dev

      - name: Instalar Cython e Buildozer
        run: |
          pip3 install --upgrade pip
          pip3 install cython
          pip3 install buildozer

      - name: Instalar Android SDK e NDK
        run: |
          mkdir -p $HOME/.buildozer/android/platform
          cd $HOME/.buildozer/android/platform
          wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O cmdline-tools.zip
          unzip cmdline-tools.zip -d cmdline-tools-temp
          mkdir -p cmdline-tools/latest
          mv cmdline-tools-temp/cmdline-tools/* cmdline-tools/latest/
          yes | cmdline-tools/latest/bin/sdkmanager --sdk_root=$HOME/.buildozer/android/platform \
            "platform-tools" "platforms;android-31" \
            "build-tools;33.0.2" "ndk;25.1.8937393" \
            "cmdline-tools;latest"

      - name: Definir variáveis de ambiente do Android SDK
        run: |
          echo "ANDROID_HOME=$HOME/.buildozer/android/platform" >> $GITHUB_ENV
          echo "ANDROID_SDK_ROOT=$HOME/.buildozer/android/platform" >> $GITHUB_ENV
          echo "$HOME/.buildozer/android/platform/platform-tools" >> $GITHUB_PATH
          echo "$HOME/.buildozer/android/platform/build-tools/33.0.2" >> $GITHUB_PATH
          echo "$HOME/.buildozer/android/platform/cmdline-tools/latest/bin" >> $GITHUB_PATH

      - name: Compilar APK com Buildozer
        run: |
          buildozer android debug

      - name: Fazer upload do APK
        uses: actions/upload-artifact@v4
        with:
          name: vs-creator-apk
          path: bin/*.apk
          
