name: Build APK com Buildozer

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Configurar ambiente
      run: |
        sudo DEBIAN_FRONTEND=noninteractive apt-get -qq update
        sudo DEBIAN_FRONTEND=noninteractive apt-get -qq install -y \
          python3-pip git zip unzip openjdk-17-jdk libffi-dev zlib1g-dev libssl-dev
        python3 -m pip install --quiet --upgrade pip setuptools wheel
        python3 -m pip install --quiet buildozer cython==0.29.36

    - name: Configurar Android
      run: |
        mkdir -p ~/.android
        touch ~/.android/repositories.cfg
        echo "sdk.dir=/usr/local/lib/android/sdk" > local.properties

    - name: Limpeza de espaço
      run: |
        sudo apt-get clean
        sudo rm -rf /usr/local/lib/android/sdk/emulator/
        df -h

    - name: Preparar buildozer.spec
      run: |
        # Forçar arquiteturas modernas
        sed -i 's/android.arch =/android.archs =/' buildozer.spec
        sed -i 's/p4a.branch = master/p4a.branch = kivy/' buildozer.spec
        echo "=== buildozer.spec ==="
        cat buildozer.spec

    - name: Compilar APK
      id: build-apk
      run: |
        set -x  # Modo debug ativado
        
        # Instalar dependências exatas do projeto
        pip install kivy==2.3.0
        
        # Build com log detalhado
        buildozer -v android debug > >(tee buildozer.log) 2> >(tee buildozer.err >&2) || true
        
        # Localizar APK
        APK_PATH=$(find . -name "*.apk" -type f | head -n1)
        
        if [ -z "$APK_PATH" ]; then
          echo "::error::❌ Falha na compilação!"
          echo "=== ERROS ==="
          cat buildozer.err
          echo "=== LOG COMPLETO ==="
          cat buildozer.log
          exit 1
        else
          echo "::notice::✅ APK gerado em: ${APK_PATH}"
          mkdir -p deployment
          cp "$APK_PATH" deployment/app-debug.apk
          echo "apk_path=deployment/app-debug.apk" >> $GITHUB_OUTPUT
        fi

    - name: Upload APK
      if: steps.build-apk.outputs.apk_path
      uses: actions/upload-artifact@v4
      with:
        name: vscreator-app
        path: ${{ steps.build-apk.outputs.apk_path }}
