name: Build VS Creator APK

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Instalar dependências do sistema
        run: |
          sudo apt update
          sudo apt install -y build-essential git zip unzip \
            openjdk-17-jdk python3 python3-pip \
            libstdc++6 libgtk-3-dev libffi-dev \
            libssl-dev libsqlite3-dev zlib1g-dev \
            libjpeg-dev libfreetype6-dev libncurses5-dev

      - name: Instalar Cython e Buildozer
        run: |
          pip3 install --upgrade pip
          pip3 install cython
          pip3 install buildozer

      - name: Compilar APK com Buildozer
        run: |
          buildozer android debug

      - name: Fazer upload do APK
        uses: actions/upload-artifact@v4
        with:
          name: vs-creator-apk
          path: bin/*.apk
          
