name: Build APK com Buildozer

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
    - uses: actions/checkout@v4

    - name: Configurar ambiente básico
      run: |
        sudo DEBIAN_FRONTEND=noninteractive apt-get -qq update
        sudo DEBIAN_FRONTEND=noninteractive apt-get -qq install -y \
          python3-pip git zip unzip openjdk-17-jdk libffi-dev zlib1g-dev libssl-dev
        python3 -m pip install --quiet --upgrade pip setuptools wheel
        python3 -m pip install --quiet buildozer cython==0.29.36 kivy==2.3.0

    - name: Configurar Android SDK/NDK
      run: |
        mkdir -p ~/.android
        touch ~/.android/repositories.cfg
        echo "sdk.dir=/usr/local/lib/android/sdk" > local.properties
        echo "ndk.dir=/usr/local/lib/android/sdk/ndk/25b" >> local.properties

    - name: Limpeza de espaço
      run: |
        sudo apt-get clean
        sudo rm -rf /usr/local/lib/android/sdk/emulator/
        sudo rm -rf /usr/local/lib/android/sdk/tools/
        df -h

    - name: Preparar buildozer.spec
      run: |
        # Garantir configurações modernas
        sed -i 's/android.arch =/android.archs =/' buildozer.spec
        sed -i 's/p4a.branch = master/p4a.branch = kivy/' buildozer.spec
        sed -i 's/android.sdk = .*/android.sdk_version = 33/' buildozer.spec
        sed -i 's/android.ndk = .*/android.ndk_version = 25b/' buildozer.spec
        
        echo "=== CONFIG VERIFICADA ==="
        grep -E 'android.(archs|sdk_version|ndk_version)' buildozer.spec

    - name: Compilar APK (com fallback completo)
      id: build-apk
      run: |
        set -exo pipefail
        
        # Configurações críticas de ambiente
        export BUILD_FAILURE=0
        export P4A_RELEASE_KEYSTORE=~/.keystore
        export P4A_RELEASE_KEYSTORE_PASSWD=android
        export P4A_RELEASE_KEYALIAS_PASSWD=android
        export P4A_RELEASE_KEYALIAS=androiddebugkey
        
        # Execução com tratamento robusto de erros
        timeout 20m buildozer -v android debug 2>&1 | tee buildozer.log || export BUILD_FAILURE=1
        
        if [ $BUILD_FAILURE -ne 0 ]; then
          echo "::warning::⚠️ Buildozer retornou erro, verificando logs..."
          grep -i error buildozer.log || true
        fi

        # Busca inteligente do APK em múltiplos locais
        APK_PATH=$(find . -name "*.apk" -type f | head -n1)
        [ -z "$APK_PATH" ] && APK_PATH=$(find . -path "*bin/*.apk" -type f | head -n1)
        
        if [ -f "$APK_PATH" ]; then
          echo "::notice::✅ APK gerado em: ${APK_PATH}"
          mkdir -p deployment
          cp "$APK_PATH" deployment/app-debug.apk
          echo "apk_path=deployment/app-debug.apk" >> $GITHUB_OUTPUT
        else
          echo "::error::❌ Falha crítica - Nenhum APK encontrado!"
          echo "=== ÚLTIMOS 50 LINHAS DO LOG ==="
          tail -n 50 buildozer.log
          echo "=== ARQUIVOS GERADOS ==="
          find .buildozer -type f | head -20
          exit 1
        fi

    - name: Upload APK
      if: steps.build-apk.outputs.apk_path
      uses: actions/upload-artifact@v4
      with:
        name: vscreator-app
        path: ${{ steps.build-apk.outputs.apk_path }}
