name: Build APK com Buildozer

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar repositório
      uses: actions/checkout@v3

    - name: Instalar dependências
      run: |
        sudo apt update
        sudo apt install -y python3-pip git zip unzip openjdk-17-jdk
        pip install --upgrade pip
        pip install buildozer cython

    - name: Compilar APK com Buildozer
      run: |
        buildozer android debug

    - name: Upload APK gerado
      uses: actions/upload-artifact@v3
      with:
        name: vscreator-apk
        path: bin/*.apk
        
