name: Build APK

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 45

    steps:
    - uses: actions/checkout@v4

    - name: Instalar dependências
      run: |
        sudo apt-get update -qq
        sudo apt-get install -y --no-install-recommends \
          python3-pip \
          openjdk-17-jdk \
          libffi-dev \
          zlib1g-dev \
          unzip \
          ffmpeg
        python3 -m pip install --quiet --upgrade pip setuptools wheel
        python3 -m pip install --quiet buildozer cython==0.29.36

    - name: Configurar ambiente Android
      run: |
        mkdir -p ~/.android
        touch ~/.android/repositories.cfg
        echo "sdk.dir=/usr/local/lib/android/sdk" > local.properties

    - name: Limpar cache
      run: |
        sudo apt-get clean
        sudo rm -rf /var/lib/apt/lists/*

    - name: Compilar APK
      run: |
        buildozer -v android debug 2>&1 | tee build.log
        ls -la bin/

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: vscreator-app
        path: bin/*.apk
        if-no-files-found: error
