name: Build APK com Buildozer

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Configurar ambiente
      run: |
        sudo DEBIAN_FRONTEND=noninteractive apt-get -qq update
        sudo DEBIAN_FRONTEND=noninteractive apt-get -qq install -y \
          python3-pip git zip unzip openjdk-17-jdk libffi-dev zlib1g-dev libssl-dev
        python3 -m pip install --quiet --upgrade pip setuptools wheel
        python3 -m pip install --quiet buildozer cython==0.29.36 kivy==2.3.0

    - name: Configurar Android SDK
      run: |
        mkdir -p ~/.android
        touch ~/.android/repositories.cfg
        echo "sdk.dir=/usr/local/lib/android/sdk" > local.properties

    - name: Preparar buildozer.spec
      run: |
        # Atualizar para formato moderno
        sed -i 's/android.arch =/android.archs =/' buildozer.spec
        sed -i 's/p4a.branch = master/p4a.branch = kivy/' buildozer.spec
        sed -i 's/android.sdk = .*/android.sdk_version = 33/' buildozer.spec
        echo "=== CONFIGURAÇÃO ATUALIZADA ==="
        cat buildozer.spec

    - name: Compilar APK (com fallback)
      id: build-apk
      run: |
        set -ex
        
        # Solução definitiva para o python-for-android
        export P4A_RELEASE_KEYSTORE=~/.keystore
        export P4A_RELEASE_KEYSTORE_PASSWD=android
        export P4A_RELEASE_KEYALIAS_PASSWD=android
        export P4A_RELEASE_KEYALIAS=androiddebugkey
        
        # Build com tratamento robusto de erros
        buildozer android debug 2>&1 | tee buildozer.log || true
        
        # Localização inteligente do APK
        APK_PATH=$(find . -path "*bin/*.apk" -type f | head -n1)
        [ -z "$APK_PATH" ] && APK_PATH=$(find . -name "*.apk" -type f | head -n1)
        
        if [ -f "$APK_PATH" ]; then
          echo "::notice::✅ APK gerado com sucesso!"
          mkdir -p deployment
          cp "$APK_PATH" deployment/app-debug.apk
          echo "apk_path=deployment/app-debug.apk" >> $GITHUB_OUTPUT
        else
          echo "::error::❌ Falha na compilação. Logs:"
          cat buildozer.log
          exit 1
        fi

    - name: Upload APK
      if: steps.build-apk.outputs.apk_path
      uses: actions/upload-artifact@v4
      with:
        name: vscreator-app
        path: ${{ steps.build-apk.outputs.apk_path }}
