name: Build APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Compilar APK com Buildozer
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Instalar dependências
        run: |
          sudo apt update
          sudo apt install -y python3-pip zip unzip openjdk-17-jdk
          python3 -m pip install --upgrade pip
          pip install buildozer cython virtualenv

      - name: Configurar variáveis de ambiente Android
        run: |
          echo "export PATH=$HOME/.buildozer/android/platform/android-sdk/platform-tools:$PATH" >> $GITHUB_ENV
          echo "export PATH=$HOME/.buildozer/android/platform/android-sdk/tools:$PATH" >> $GITHUB_ENV

      - name: Criar APK com Buildozer
        run: |
          buildozer android debug

      - name: Upload do APK
        uses: actions/upload-artifact@v3
        with:
          name: vscreator-apk
          path: bin/*.apk
          
